export const ORGANIZATION_REPOSITORY = Symbol('ORGANIZATION_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const SHOPPING_CART_REPOSITORY = Symbol('SHOPPING_CART_REPOSITORY');
export const RESERVATION_SERVICE = Symbol('RESERVATION_SERVICE');
